### ISSUE TITLE
Design is Not RESPONSIVE in landscape mode

### ISSUE THREAD

**Issue by Manishmg3994** [firgia/FE-Phone-Authentication#2]
Please Do Some Modification and replace the sliverlist with sliver builder to overcome bottom overflow or rendering flex errors so that design response better in landscape as well as in portrait

**Comment by Manishmg3994** [comment]
waiting for response

**Comment by Manishmg3994** [comment]
please do some changes

**Comment by SiddharthChitrala** [comment]
the repo is missing
